name: err
version: 0.2.0
synopsis: To Err is Human - Error Handling with loquacious error messages.
maintainer: Imuli <i@imu.li>
github: imuli/err
license: PublicDomain
license-file: UNLICENSE
category: Error Handling
description: Errors with pretty (and localisable) messages that can be easily decomposed.

ghc-options: -Wall

dependencies:
  - base >= 4.11 && < 5.0
  - loquacious ^>= 0.1
  - prettyprinter >= 1.2 && < 2.0
  - text >= 1.0 && < 2.0

library:
  source-dirs: src
